#!/bin/bash
#SBATCH -A test                             # 自己所属的账户 (不要改)
#SBATCH -J VAN_test  # 所运行的任务名称 (自己取)
#SBATCH -N 1                                # 占用的节点数（根据代码要求确定）
#SBATCH --ntasks-per-node=1                 # 运行的进程数（根据代码要求确定）
#SBATCH --cpus-per-task=1                  # 每个进程的CPU核数 （根据代码要求确定）
#SBATCH --gres=gpu:1                        # 占用的GPU卡数 （根据代码要求确定）
#SBATCH -p chromium                           # 任务运行所在的分区 (根据代码要求确定，gpu为gpu分区，gpu4为4卡gpu分区，cpu为cpu分区)
#SBATCH -t 0-00:20:00                     # 运行的最长时间 day-hour:minute:second，但是请按需设置，不要浪费过多时间，否则影响系统效率
#SBATCH -o test.out     # 打印输出的文件

source /home/TUE/20180170/miniconda3/etc/profile.d/conda.sh
source activate torch171


MODEL=van_tiny # van_{tiny, small, base, large}
DROP_PATH=0.1 # drop path rates [0.1, 0.1, 0.1, 0.2] for [tiny, small, base, large]
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 bash distributed_train.sh 8 /mnt/server-home/datasets/ImageNet/  \
	  --model $MODEL -b 128 --lr 1e-3 --drop-path $DROP_PATH

#/scratch-shared/shiwei/
